server:
  port: 8092
  
spring:
  application:
    name: mediapp-medics

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
