server:
  port: 8093
  
spring:
  application:
    name: mediapp-patients

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
