server:
  port: 8091
  
spring:
  application:
    name: mediapp-exams

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
